Repository kube-reporting/hadoop, pull requests merged in 2019-07, with the labels that each got.

#10 Add faq/openssl to image
  Dockerfile
  Dockerfile.rhel
  faq.repo
Labels: approved, lgtm, size/S

#11 added gcs-connector for hadoop
  Dockerfile
Labels: approved, lgtm, size/XS

#13 Dockerfile.okd: Add GCS connector
  Dockerfile.okd
Labels: approved, lgtm, size/XS

#14 added shaded version
  Dockerfile
Labels: approved, lgtm, size/XS

#15 Dockerfile*: Run yum update before yum install
  Dockerfile
  Dockerfile.okd
  Dockerfile.rhel
Labels: approved, size/S

#16 Dockerfile.okd: Use origin-base as base image
  Dockerfile.okd
Labels: approved, lgtm, size/XS
